triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: help.*
        capture_text: false
states:
    first:
        component: meya.text
        properties:
            text: >
                Hi, I am LegalEase, a bot who can give you legal help
                and point you in the right directions for further help.
        delay:
            relative: 1

    functions_1:
        component: meya.text
        properties:
            text: > 
                I can help you fill up a Lasting Power of Attorney (LPA) form.
                To do so, type "LPA".
        delay:
            relative: 1

    functions_2:
        component: meya.text
        properties:
            text: >
                If you have a letter from the police, or need to see a lawyer
                at a legal clinic, type "police".
        delay:
            relative: 1

    function_select:
        component: meya.text_buttons
        properties:
            text: "Please choose select one:"
            buttons:
                - text: LPA
                  action: lpa
                - text: Police
                  action: police
        transitions:
            lpa: lpa
            police: police

    lpa:
        flow: lpa

    police:
        flow: police
