triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: th(an)?ks?(\s+you|\s+u)?.*
        capture_text: false
states:
    reply:
        component: meya.random_text
        properties:
            responses:
                - No problem. Hope I have been helpful!
                - You're welcome! 😃
                - And thank *you* for using LegalEase!
                - Awww, thanks!
